### ISSUE TITLE
Issue: Can't copy paste card in canvas

### ISSUE THREAD

**Issue by dtslab** [Developer-Mike/obsidian-advanced-canvas#30]
Can't copy paste card in Canvas after latest update.

**Comment by Developer-Mike** [comment]
Thank you for reporting this critical issue! It's fixed now (in version 2.6.1).

**Comment by ronrdev** [comment]
I have this issue. 
Latest version of plugin
Not on catalyst version of Obsidian

Can't copy text from canvas card into a note in another panel. 
Using outliner.md let me drag and drop. Turned off outliner.md because I though that was the problem, but still no go.
Closed Obsidian, reopened, and it pasted, but tried from another card and would not paste. 
Turned off advanced canvas and copy paste works well.

**Comment by Developer-Mike** [comment]
What do you mean with "card" and "panel" (do you mean "node" and "tab")? I can't reproduce this issue. Please clarify your observed behaviour.

**Comment by Developer-Mike** [comment]
Thank you for the update. Because AC doesn't override anything related to the text copying and pasting, I think there was an issue outside the plugin.
